language: julia

dist: bionic

os:
  - linux

julia:
  - 1.3

addons:
  apt:
    packages:
      - python3-matplotlib

notifications:
  email:
    recipients: abel.s.siqueira@gmail.com
    on_success: never
    on_failure: change

# Should build on all branches in order to generate the preview

script:
  - julia --project -e 'using Pkg; pkg"build"'
  - bash auto-build.sh
  - julia --project -e 'using Pkg; pkg"test"'
  - julia build-site.jl
